#pragma once

#define WIN32_LEAN_AND_MEAN
#include <Windows.h>
#include <tchar.h>
#include <time.h>
#include <iostream>
#include <string>
#include <xstring>
#include <string_view>
#include <sstream>
#include <format>
#include <cassert>
#include <cstdint>
#include <cstddef>
#include <utility>
#include <type_traits>
#include <functional>
#include <optional>
#include <variant>
#include <memory>
#include <cmath>
#include <cstdlib>
#include <limits>
#include <algorithm>
#include <numeric>
#include <vector>
#include <array>
#include <map>
#include <unordered_map>
#include <set>
#include <unordered_set>
#include <queue>
#include <stack>
#include <deque>
#include <chrono>
#include <thread>
#include <mutex>
#include <atomic>
#include <fstream>
#include <filesystem>
#include <ostream>
#include <iosfwd>
#include <iomanip>
#include <cassert>
#include <wrl.h>

template<class T>
using ComPtr = Microsoft::WRL::ComPtr<T>;
